# docker-compose.yml
version: "3.8"
services:
  mysql:
    image: mysql:8.0.36
    container_name: government_supply_chain_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: government_supply_chain
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: